// Code generated by https://github.com/src-d/go-kallax. DO NOT EDIT.
// Please, do not touch the code below, and if you do, do it under your own
// risk. Take into account that all the code you write here will be completely
// erased from earth the next time you generate the kallax models.
package models

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/src-d/lookout/pb"
	"gopkg.in/src-d/go-kallax.v1"
	"gopkg.in/src-d/go-kallax.v1/types"
)

var _ types.SQLType
var _ fmt.Formatter

type modelSaveFunc func(*kallax.Store) error

// NewComment returns a new instance of Comment.
func NewComment(c pb.Comment) (record *Comment) {
	return newComment(c)
}

// GetID returns the primary key of the model.
func (r *Comment) GetID() kallax.Identifier {
	return (*kallax.ULID)(&r.ID)
}

// ColumnAddress returns the pointer to the value of the given column.
func (r *Comment) ColumnAddress(col string) (interface{}, error) {
	switch col {
	case "id":
		return (*kallax.ULID)(&r.ID), nil
	case "file":
		return &r.Comment.File, nil
	case "line":
		return &r.Comment.Line, nil
	case "text":
		return &r.Comment.Text, nil
	case "confidence":
		return &r.Comment.Confidence, nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in Comment: %s", col)
	}
}

// Value returns the value of the given column.
func (r *Comment) Value(col string) (interface{}, error) {
	switch col {
	case "id":
		return r.ID, nil
	case "file":
		return r.Comment.File, nil
	case "line":
		return r.Comment.Line, nil
	case "text":
		return r.Comment.Text, nil
	case "confidence":
		return r.Comment.Confidence, nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in Comment: %s", col)
	}
}

// NewRelationshipRecord returns a new record for the relatiobship in the given
// field.
func (r *Comment) NewRelationshipRecord(field string) (kallax.Record, error) {
	return nil, fmt.Errorf("kallax: model Comment has no relationships")
}

// SetRelationship sets the given relationship in the given field.
func (r *Comment) SetRelationship(field string, rel interface{}) error {
	return fmt.Errorf("kallax: model Comment has no relationships")
}

// CommentStore is the entity to access the records of the type Comment
// in the database.
type CommentStore struct {
	*kallax.Store
}

// NewCommentStore creates a new instance of CommentStore
// using a SQL database.
func NewCommentStore(db *sql.DB) *CommentStore {
	return &CommentStore{kallax.NewStore(db)}
}

// GenericStore returns the generic store of this store.
func (s *CommentStore) GenericStore() *kallax.Store {
	return s.Store
}

// SetGenericStore changes the generic store of this store.
func (s *CommentStore) SetGenericStore(store *kallax.Store) {
	s.Store = store
}

// Debug returns a new store that will print all SQL statements to stdout using
// the log.Printf function.
func (s *CommentStore) Debug() *CommentStore {
	return &CommentStore{s.Store.Debug()}
}

// DebugWith returns a new store that will print all SQL statements using the
// given logger function.
func (s *CommentStore) DebugWith(logger kallax.LoggerFunc) *CommentStore {
	return &CommentStore{s.Store.DebugWith(logger)}
}

// DisableCacher turns off prepared statements, which can be useful in some scenarios.
func (s *CommentStore) DisableCacher() *CommentStore {
	return &CommentStore{s.Store.DisableCacher()}
}

// Insert inserts a Comment in the database. A non-persisted object is
// required for this operation.
func (s *CommentStore) Insert(record *Comment) error {
	record.SetSaving(true)
	defer record.SetSaving(false)

	return s.Store.Insert(Schema.Comment.BaseSchema, record)
}

// Update updates the given record on the database. If the columns are given,
// only these columns will be updated. Otherwise all of them will be.
// Be very careful with this, as you will have a potentially different object
// in memory but not on the database.
// Only writable records can be updated. Writable objects are those that have
// been just inserted or retrieved using a query with no custom select fields.
func (s *CommentStore) Update(record *Comment, cols ...kallax.SchemaField) (updated int64, err error) {
	record.SetSaving(true)
	defer record.SetSaving(false)

	return s.Store.Update(Schema.Comment.BaseSchema, record, cols...)
}

// Save inserts the object if the record is not persisted, otherwise it updates
// it. Same rules of Update and Insert apply depending on the case.
func (s *CommentStore) Save(record *Comment) (updated bool, err error) {
	if !record.IsPersisted() {
		return false, s.Insert(record)
	}

	rowsUpdated, err := s.Update(record)
	if err != nil {
		return false, err
	}

	return rowsUpdated > 0, nil
}

// Delete removes the given record from the database.
func (s *CommentStore) Delete(record *Comment) error {
	return s.Store.Delete(Schema.Comment.BaseSchema, record)
}

// Find returns the set of results for the given query.
func (s *CommentStore) Find(q *CommentQuery) (*CommentResultSet, error) {
	rs, err := s.Store.Find(q)
	if err != nil {
		return nil, err
	}

	return NewCommentResultSet(rs), nil
}

// MustFind returns the set of results for the given query, but panics if there
// is any error.
func (s *CommentStore) MustFind(q *CommentQuery) *CommentResultSet {
	return NewCommentResultSet(s.Store.MustFind(q))
}

// Count returns the number of rows that would be retrieved with the given
// query.
func (s *CommentStore) Count(q *CommentQuery) (int64, error) {
	return s.Store.Count(q)
}

// MustCount returns the number of rows that would be retrieved with the given
// query, but panics if there is an error.
func (s *CommentStore) MustCount(q *CommentQuery) int64 {
	return s.Store.MustCount(q)
}

// FindOne returns the first row returned by the given query.
// `ErrNotFound` is returned if there are no results.
func (s *CommentStore) FindOne(q *CommentQuery) (*Comment, error) {
	q.Limit(1)
	q.Offset(0)
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// FindAll returns a list of all the rows returned by the given query.
func (s *CommentStore) FindAll(q *CommentQuery) ([]*Comment, error) {
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	return rs.All()
}

// MustFindOne returns the first row retrieved by the given query. It panics
// if there is an error or if there are no rows.
func (s *CommentStore) MustFindOne(q *CommentQuery) *Comment {
	record, err := s.FindOne(q)
	if err != nil {
		panic(err)
	}
	return record
}

// Reload refreshes the Comment with the data in the database and
// makes it writable.
func (s *CommentStore) Reload(record *Comment) error {
	return s.Store.Reload(Schema.Comment.BaseSchema, record)
}

// Transaction executes the given callback in a transaction and rollbacks if
// an error is returned.
// The transaction is only open in the store passed as a parameter to the
// callback.
func (s *CommentStore) Transaction(callback func(*CommentStore) error) error {
	if callback == nil {
		return kallax.ErrInvalidTxCallback
	}

	return s.Store.Transaction(func(store *kallax.Store) error {
		return callback(&CommentStore{store})
	})
}

// CommentQuery is the object used to create queries for the Comment
// entity.
type CommentQuery struct {
	*kallax.BaseQuery
}

// NewCommentQuery returns a new instance of CommentQuery.
func NewCommentQuery() *CommentQuery {
	return &CommentQuery{
		BaseQuery: kallax.NewBaseQuery(Schema.Comment.BaseSchema),
	}
}

// Select adds columns to select in the query.
func (q *CommentQuery) Select(columns ...kallax.SchemaField) *CommentQuery {
	if len(columns) == 0 {
		return q
	}
	q.BaseQuery.Select(columns...)
	return q
}

// SelectNot excludes columns from being selected in the query.
func (q *CommentQuery) SelectNot(columns ...kallax.SchemaField) *CommentQuery {
	q.BaseQuery.SelectNot(columns...)
	return q
}

// Copy returns a new identical copy of the query. Remember queries are mutable
// so make a copy any time you need to reuse them.
func (q *CommentQuery) Copy() *CommentQuery {
	return &CommentQuery{
		BaseQuery: q.BaseQuery.Copy(),
	}
}

// Order adds order clauses to the query for the given columns.
func (q *CommentQuery) Order(cols ...kallax.ColumnOrder) *CommentQuery {
	q.BaseQuery.Order(cols...)
	return q
}

// BatchSize sets the number of items to fetch per batch when there are 1:N
// relationships selected in the query.
func (q *CommentQuery) BatchSize(size uint64) *CommentQuery {
	q.BaseQuery.BatchSize(size)
	return q
}

// Limit sets the max number of items to retrieve.
func (q *CommentQuery) Limit(n uint64) *CommentQuery {
	q.BaseQuery.Limit(n)
	return q
}

// Offset sets the number of items to skip from the result set of items.
func (q *CommentQuery) Offset(n uint64) *CommentQuery {
	q.BaseQuery.Offset(n)
	return q
}

// Where adds a condition to the query. All conditions added are concatenated
// using a logical AND.
func (q *CommentQuery) Where(cond kallax.Condition) *CommentQuery {
	q.BaseQuery.Where(cond)
	return q
}

// FindByID adds a new filter to the query that will require that
// the ID property is equal to one of the passed values; if no passed values,
// it will do nothing.
func (q *CommentQuery) FindByID(v ...kallax.ULID) *CommentQuery {
	if len(v) == 0 {
		return q
	}
	values := make([]interface{}, len(v))
	for i, val := range v {
		values[i] = val
	}
	return q.Where(kallax.In(Schema.Comment.ID, values...))
}

// FindByFile adds a new filter to the query that will require that
// the File property is equal to the passed value.
func (q *CommentQuery) FindByFile(v string) *CommentQuery {
	return q.Where(kallax.Eq(Schema.Comment.File, v))
}

// FindByLine adds a new filter to the query that will require that
// the Line property is equal to the passed value.
func (q *CommentQuery) FindByLine(cond kallax.ScalarCond, v int32) *CommentQuery {
	return q.Where(cond(Schema.Comment.Line, v))
}

// FindByText adds a new filter to the query that will require that
// the Text property is equal to the passed value.
func (q *CommentQuery) FindByText(v string) *CommentQuery {
	return q.Where(kallax.Eq(Schema.Comment.Text, v))
}

// FindByConfidence adds a new filter to the query that will require that
// the Confidence property is equal to the passed value.
func (q *CommentQuery) FindByConfidence(cond kallax.ScalarCond, v uint32) *CommentQuery {
	return q.Where(cond(Schema.Comment.Confidence, v))
}

// CommentResultSet is the set of results returned by a query to the
// database.
type CommentResultSet struct {
	ResultSet kallax.ResultSet
	last      *Comment
	lastErr   error
}

// NewCommentResultSet creates a new result set for rows of the type
// Comment.
func NewCommentResultSet(rs kallax.ResultSet) *CommentResultSet {
	return &CommentResultSet{ResultSet: rs}
}

// Next fetches the next item in the result set and returns true if there is
// a next item.
// The result set is closed automatically when there are no more items.
func (rs *CommentResultSet) Next() bool {
	if !rs.ResultSet.Next() {
		rs.lastErr = rs.ResultSet.Close()
		rs.last = nil
		return false
	}

	var record kallax.Record
	record, rs.lastErr = rs.ResultSet.Get(Schema.Comment.BaseSchema)
	if rs.lastErr != nil {
		rs.last = nil
	} else {
		var ok bool
		rs.last, ok = record.(*Comment)
		if !ok {
			rs.lastErr = fmt.Errorf("kallax: unable to convert record to *Comment")
			rs.last = nil
		}
	}

	return true
}

// Get retrieves the last fetched item from the result set and the last error.
func (rs *CommentResultSet) Get() (*Comment, error) {
	return rs.last, rs.lastErr
}

// ForEach iterates over the complete result set passing every record found to
// the given callback. It is possible to stop the iteration by returning
// `kallax.ErrStop` in the callback.
// Result set is always closed at the end.
func (rs *CommentResultSet) ForEach(fn func(*Comment) error) error {
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return err
		}

		if err := fn(record); err != nil {
			if err == kallax.ErrStop {
				return rs.Close()
			}

			return err
		}
	}
	return nil
}

// All returns all records on the result set and closes the result set.
func (rs *CommentResultSet) All() ([]*Comment, error) {
	var result []*Comment
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return nil, err
		}
		result = append(result, record)
	}
	return result, nil
}

// One returns the first record on the result set and closes the result set.
func (rs *CommentResultSet) One() (*Comment, error) {
	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// Err returns the last error occurred.
func (rs *CommentResultSet) Err() error {
	return rs.lastErr
}

// Close closes the result set.
func (rs *CommentResultSet) Close() error {
	return rs.ResultSet.Close()
}

// NewReviewEvent returns a new instance of ReviewEvent.
func NewReviewEvent(e *pb.ReviewEvent) (record *ReviewEvent) {
	return newReviewEvent(e)
}

// GetID returns the primary key of the model.
func (r *ReviewEvent) GetID() kallax.Identifier {
	return (*kallax.ULID)(&r.ID)
}

// ColumnAddress returns the pointer to the value of the given column.
func (r *ReviewEvent) ColumnAddress(col string) (interface{}, error) {
	switch col {
	case "id":
		return (*kallax.ULID)(&r.ID), nil
	case "status":
		return (*string)(&r.Status), nil
	case "provider":
		return &r.ReviewEvent.Provider, nil
	case "internal_id":
		return &r.ReviewEvent.InternalID, nil
	case "created_at":
		return &r.ReviewEvent.CreatedAt, nil
	case "updated_at":
		return &r.ReviewEvent.UpdatedAt, nil
	case "is_mergeable":
		return &r.ReviewEvent.IsMergeable, nil
	case "source":
		return types.JSON(&r.ReviewEvent.Source), nil
	case "merge":
		return types.JSON(&r.ReviewEvent.Merge), nil
	case "configuration":
		return types.JSON(&r.ReviewEvent.Configuration), nil
	case "base":
		return types.JSON(&r.ReviewEvent.CommitRevision.Base), nil
	case "head":
		return types.JSON(&r.ReviewEvent.CommitRevision.Head), nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in ReviewEvent: %s", col)
	}
}

// Value returns the value of the given column.
func (r *ReviewEvent) Value(col string) (interface{}, error) {
	switch col {
	case "id":
		return r.ID, nil
	case "status":
		return (string)(r.Status), nil
	case "provider":
		return r.ReviewEvent.Provider, nil
	case "internal_id":
		return r.ReviewEvent.InternalID, nil
	case "created_at":
		return r.ReviewEvent.CreatedAt, nil
	case "updated_at":
		return r.ReviewEvent.UpdatedAt, nil
	case "is_mergeable":
		return r.ReviewEvent.IsMergeable, nil
	case "source":
		return types.JSON(r.ReviewEvent.Source), nil
	case "merge":
		return types.JSON(r.ReviewEvent.Merge), nil
	case "configuration":
		return types.JSON(r.ReviewEvent.Configuration), nil
	case "base":
		return types.JSON(r.ReviewEvent.CommitRevision.Base), nil
	case "head":
		return types.JSON(r.ReviewEvent.CommitRevision.Head), nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in ReviewEvent: %s", col)
	}
}

// NewRelationshipRecord returns a new record for the relatiobship in the given
// field.
func (r *ReviewEvent) NewRelationshipRecord(field string) (kallax.Record, error) {
	return nil, fmt.Errorf("kallax: model ReviewEvent has no relationships")
}

// SetRelationship sets the given relationship in the given field.
func (r *ReviewEvent) SetRelationship(field string, rel interface{}) error {
	return fmt.Errorf("kallax: model ReviewEvent has no relationships")
}

// ReviewEventStore is the entity to access the records of the type ReviewEvent
// in the database.
type ReviewEventStore struct {
	*kallax.Store
}

// NewReviewEventStore creates a new instance of ReviewEventStore
// using a SQL database.
func NewReviewEventStore(db *sql.DB) *ReviewEventStore {
	return &ReviewEventStore{kallax.NewStore(db)}
}

// GenericStore returns the generic store of this store.
func (s *ReviewEventStore) GenericStore() *kallax.Store {
	return s.Store
}

// SetGenericStore changes the generic store of this store.
func (s *ReviewEventStore) SetGenericStore(store *kallax.Store) {
	s.Store = store
}

// Debug returns a new store that will print all SQL statements to stdout using
// the log.Printf function.
func (s *ReviewEventStore) Debug() *ReviewEventStore {
	return &ReviewEventStore{s.Store.Debug()}
}

// DebugWith returns a new store that will print all SQL statements using the
// given logger function.
func (s *ReviewEventStore) DebugWith(logger kallax.LoggerFunc) *ReviewEventStore {
	return &ReviewEventStore{s.Store.DebugWith(logger)}
}

// DisableCacher turns off prepared statements, which can be useful in some scenarios.
func (s *ReviewEventStore) DisableCacher() *ReviewEventStore {
	return &ReviewEventStore{s.Store.DisableCacher()}
}

// Insert inserts a ReviewEvent in the database. A non-persisted object is
// required for this operation.
func (s *ReviewEventStore) Insert(record *ReviewEvent) error {
	record.SetSaving(true)
	defer record.SetSaving(false)

	record.CreatedAt = record.CreatedAt.Truncate(time.Microsecond)
	record.UpdatedAt = record.UpdatedAt.Truncate(time.Microsecond)

	return s.Store.Insert(Schema.ReviewEvent.BaseSchema, record)
}

// Update updates the given record on the database. If the columns are given,
// only these columns will be updated. Otherwise all of them will be.
// Be very careful with this, as you will have a potentially different object
// in memory but not on the database.
// Only writable records can be updated. Writable objects are those that have
// been just inserted or retrieved using a query with no custom select fields.
func (s *ReviewEventStore) Update(record *ReviewEvent, cols ...kallax.SchemaField) (updated int64, err error) {
	record.CreatedAt = record.CreatedAt.Truncate(time.Microsecond)
	record.UpdatedAt = record.UpdatedAt.Truncate(time.Microsecond)

	record.SetSaving(true)
	defer record.SetSaving(false)

	return s.Store.Update(Schema.ReviewEvent.BaseSchema, record, cols...)
}

// Save inserts the object if the record is not persisted, otherwise it updates
// it. Same rules of Update and Insert apply depending on the case.
func (s *ReviewEventStore) Save(record *ReviewEvent) (updated bool, err error) {
	if !record.IsPersisted() {
		return false, s.Insert(record)
	}

	rowsUpdated, err := s.Update(record)
	if err != nil {
		return false, err
	}

	return rowsUpdated > 0, nil
}

// Delete removes the given record from the database.
func (s *ReviewEventStore) Delete(record *ReviewEvent) error {
	return s.Store.Delete(Schema.ReviewEvent.BaseSchema, record)
}

// Find returns the set of results for the given query.
func (s *ReviewEventStore) Find(q *ReviewEventQuery) (*ReviewEventResultSet, error) {
	rs, err := s.Store.Find(q)
	if err != nil {
		return nil, err
	}

	return NewReviewEventResultSet(rs), nil
}

// MustFind returns the set of results for the given query, but panics if there
// is any error.
func (s *ReviewEventStore) MustFind(q *ReviewEventQuery) *ReviewEventResultSet {
	return NewReviewEventResultSet(s.Store.MustFind(q))
}

// Count returns the number of rows that would be retrieved with the given
// query.
func (s *ReviewEventStore) Count(q *ReviewEventQuery) (int64, error) {
	return s.Store.Count(q)
}

// MustCount returns the number of rows that would be retrieved with the given
// query, but panics if there is an error.
func (s *ReviewEventStore) MustCount(q *ReviewEventQuery) int64 {
	return s.Store.MustCount(q)
}

// FindOne returns the first row returned by the given query.
// `ErrNotFound` is returned if there are no results.
func (s *ReviewEventStore) FindOne(q *ReviewEventQuery) (*ReviewEvent, error) {
	q.Limit(1)
	q.Offset(0)
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// FindAll returns a list of all the rows returned by the given query.
func (s *ReviewEventStore) FindAll(q *ReviewEventQuery) ([]*ReviewEvent, error) {
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	return rs.All()
}

// MustFindOne returns the first row retrieved by the given query. It panics
// if there is an error or if there are no rows.
func (s *ReviewEventStore) MustFindOne(q *ReviewEventQuery) *ReviewEvent {
	record, err := s.FindOne(q)
	if err != nil {
		panic(err)
	}
	return record
}

// Reload refreshes the ReviewEvent with the data in the database and
// makes it writable.
func (s *ReviewEventStore) Reload(record *ReviewEvent) error {
	return s.Store.Reload(Schema.ReviewEvent.BaseSchema, record)
}

// Transaction executes the given callback in a transaction and rollbacks if
// an error is returned.
// The transaction is only open in the store passed as a parameter to the
// callback.
func (s *ReviewEventStore) Transaction(callback func(*ReviewEventStore) error) error {
	if callback == nil {
		return kallax.ErrInvalidTxCallback
	}

	return s.Store.Transaction(func(store *kallax.Store) error {
		return callback(&ReviewEventStore{store})
	})
}

// ReviewEventQuery is the object used to create queries for the ReviewEvent
// entity.
type ReviewEventQuery struct {
	*kallax.BaseQuery
}

// NewReviewEventQuery returns a new instance of ReviewEventQuery.
func NewReviewEventQuery() *ReviewEventQuery {
	return &ReviewEventQuery{
		BaseQuery: kallax.NewBaseQuery(Schema.ReviewEvent.BaseSchema),
	}
}

// Select adds columns to select in the query.
func (q *ReviewEventQuery) Select(columns ...kallax.SchemaField) *ReviewEventQuery {
	if len(columns) == 0 {
		return q
	}
	q.BaseQuery.Select(columns...)
	return q
}

// SelectNot excludes columns from being selected in the query.
func (q *ReviewEventQuery) SelectNot(columns ...kallax.SchemaField) *ReviewEventQuery {
	q.BaseQuery.SelectNot(columns...)
	return q
}

// Copy returns a new identical copy of the query. Remember queries are mutable
// so make a copy any time you need to reuse them.
func (q *ReviewEventQuery) Copy() *ReviewEventQuery {
	return &ReviewEventQuery{
		BaseQuery: q.BaseQuery.Copy(),
	}
}

// Order adds order clauses to the query for the given columns.
func (q *ReviewEventQuery) Order(cols ...kallax.ColumnOrder) *ReviewEventQuery {
	q.BaseQuery.Order(cols...)
	return q
}

// BatchSize sets the number of items to fetch per batch when there are 1:N
// relationships selected in the query.
func (q *ReviewEventQuery) BatchSize(size uint64) *ReviewEventQuery {
	q.BaseQuery.BatchSize(size)
	return q
}

// Limit sets the max number of items to retrieve.
func (q *ReviewEventQuery) Limit(n uint64) *ReviewEventQuery {
	q.BaseQuery.Limit(n)
	return q
}

// Offset sets the number of items to skip from the result set of items.
func (q *ReviewEventQuery) Offset(n uint64) *ReviewEventQuery {
	q.BaseQuery.Offset(n)
	return q
}

// Where adds a condition to the query. All conditions added are concatenated
// using a logical AND.
func (q *ReviewEventQuery) Where(cond kallax.Condition) *ReviewEventQuery {
	q.BaseQuery.Where(cond)
	return q
}

// FindByID adds a new filter to the query that will require that
// the ID property is equal to one of the passed values; if no passed values,
// it will do nothing.
func (q *ReviewEventQuery) FindByID(v ...kallax.ULID) *ReviewEventQuery {
	if len(v) == 0 {
		return q
	}
	values := make([]interface{}, len(v))
	for i, val := range v {
		values[i] = val
	}
	return q.Where(kallax.In(Schema.ReviewEvent.ID, values...))
}

// FindByStatus adds a new filter to the query that will require that
// the Status property is equal to the passed value.
func (q *ReviewEventQuery) FindByStatus(v EventStatus) *ReviewEventQuery {
	return q.Where(kallax.Eq(Schema.ReviewEvent.Status, v))
}

// FindByProvider adds a new filter to the query that will require that
// the Provider property is equal to the passed value.
func (q *ReviewEventQuery) FindByProvider(v string) *ReviewEventQuery {
	return q.Where(kallax.Eq(Schema.ReviewEvent.Provider, v))
}

// FindByInternalID adds a new filter to the query that will require that
// the InternalID property is equal to the passed value.
func (q *ReviewEventQuery) FindByInternalID(v string) *ReviewEventQuery {
	return q.Where(kallax.Eq(Schema.ReviewEvent.InternalID, v))
}

// FindByCreatedAt adds a new filter to the query that will require that
// the CreatedAt property is equal to the passed value.
func (q *ReviewEventQuery) FindByCreatedAt(cond kallax.ScalarCond, v time.Time) *ReviewEventQuery {
	return q.Where(cond(Schema.ReviewEvent.CreatedAt, v))
}

// FindByUpdatedAt adds a new filter to the query that will require that
// the UpdatedAt property is equal to the passed value.
func (q *ReviewEventQuery) FindByUpdatedAt(cond kallax.ScalarCond, v time.Time) *ReviewEventQuery {
	return q.Where(cond(Schema.ReviewEvent.UpdatedAt, v))
}

// FindByIsMergeable adds a new filter to the query that will require that
// the IsMergeable property is equal to the passed value.
func (q *ReviewEventQuery) FindByIsMergeable(v bool) *ReviewEventQuery {
	return q.Where(kallax.Eq(Schema.ReviewEvent.IsMergeable, v))
}

// ReviewEventResultSet is the set of results returned by a query to the
// database.
type ReviewEventResultSet struct {
	ResultSet kallax.ResultSet
	last      *ReviewEvent
	lastErr   error
}

// NewReviewEventResultSet creates a new result set for rows of the type
// ReviewEvent.
func NewReviewEventResultSet(rs kallax.ResultSet) *ReviewEventResultSet {
	return &ReviewEventResultSet{ResultSet: rs}
}

// Next fetches the next item in the result set and returns true if there is
// a next item.
// The result set is closed automatically when there are no more items.
func (rs *ReviewEventResultSet) Next() bool {
	if !rs.ResultSet.Next() {
		rs.lastErr = rs.ResultSet.Close()
		rs.last = nil
		return false
	}

	var record kallax.Record
	record, rs.lastErr = rs.ResultSet.Get(Schema.ReviewEvent.BaseSchema)
	if rs.lastErr != nil {
		rs.last = nil
	} else {
		var ok bool
		rs.last, ok = record.(*ReviewEvent)
		if !ok {
			rs.lastErr = fmt.Errorf("kallax: unable to convert record to *ReviewEvent")
			rs.last = nil
		}
	}

	return true
}

// Get retrieves the last fetched item from the result set and the last error.
func (rs *ReviewEventResultSet) Get() (*ReviewEvent, error) {
	return rs.last, rs.lastErr
}

// ForEach iterates over the complete result set passing every record found to
// the given callback. It is possible to stop the iteration by returning
// `kallax.ErrStop` in the callback.
// Result set is always closed at the end.
func (rs *ReviewEventResultSet) ForEach(fn func(*ReviewEvent) error) error {
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return err
		}

		if err := fn(record); err != nil {
			if err == kallax.ErrStop {
				return rs.Close()
			}

			return err
		}
	}
	return nil
}

// All returns all records on the result set and closes the result set.
func (rs *ReviewEventResultSet) All() ([]*ReviewEvent, error) {
	var result []*ReviewEvent
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return nil, err
		}
		result = append(result, record)
	}
	return result, nil
}

// One returns the first record on the result set and closes the result set.
func (rs *ReviewEventResultSet) One() (*ReviewEvent, error) {
	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// Err returns the last error occurred.
func (rs *ReviewEventResultSet) Err() error {
	return rs.lastErr
}

// Close closes the result set.
func (rs *ReviewEventResultSet) Close() error {
	return rs.ResultSet.Close()
}

type schema struct {
	Comment     *schemaComment
	ReviewEvent *schemaReviewEvent
}

type schemaComment struct {
	*kallax.BaseSchema
	ID         kallax.SchemaField
	File       kallax.SchemaField
	Line       kallax.SchemaField
	Text       kallax.SchemaField
	Confidence kallax.SchemaField
}

type schemaReviewEvent struct {
	*kallax.BaseSchema
	ID            kallax.SchemaField
	Status        kallax.SchemaField
	Provider      kallax.SchemaField
	InternalID    kallax.SchemaField
	CreatedAt     kallax.SchemaField
	UpdatedAt     kallax.SchemaField
	IsMergeable   kallax.SchemaField
	Source        *schemaReviewEventSource
	Merge         *schemaReviewEventMerge
	Configuration *schemaReviewEventConfiguration
	Base          *schemaReviewEventBase
	Head          *schemaReviewEventHead
}

type schemaReviewEventBase struct {
	*kallax.BaseSchemaField
	InternalRepositoryURL kallax.SchemaField
	ReferenceName         kallax.SchemaField
	Hash                  kallax.SchemaField
}

type schemaReviewEventConfiguration struct {
	*kallax.BaseSchemaField
	Fields kallax.SchemaField
}

type schemaReviewEventHead struct {
	*kallax.BaseSchemaField
	InternalRepositoryURL kallax.SchemaField
	ReferenceName         kallax.SchemaField
	Hash                  kallax.SchemaField
}

type schemaReviewEventMerge struct {
	*kallax.BaseSchemaField
	InternalRepositoryURL kallax.SchemaField
	ReferenceName         kallax.SchemaField
	Hash                  kallax.SchemaField
}

type schemaReviewEventSource struct {
	*kallax.BaseSchemaField
	InternalRepositoryURL kallax.SchemaField
	ReferenceName         kallax.SchemaField
	Hash                  kallax.SchemaField
}

var Schema = &schema{
	Comment: &schemaComment{
		BaseSchema: kallax.NewBaseSchema(
			"comment",
			"__comment",
			kallax.NewSchemaField("id"),
			kallax.ForeignKeys{},
			func() kallax.Record {
				return new(Comment)
			},
			false,
			kallax.NewSchemaField("id"),
			kallax.NewSchemaField("file"),
			kallax.NewSchemaField("line"),
			kallax.NewSchemaField("text"),
			kallax.NewSchemaField("confidence"),
		),
		ID:         kallax.NewSchemaField("id"),
		File:       kallax.NewSchemaField("file"),
		Line:       kallax.NewSchemaField("line"),
		Text:       kallax.NewSchemaField("text"),
		Confidence: kallax.NewSchemaField("confidence"),
	},
	ReviewEvent: &schemaReviewEvent{
		BaseSchema: kallax.NewBaseSchema(
			"review_event",
			"__reviewevent",
			kallax.NewSchemaField("id"),
			kallax.ForeignKeys{},
			func() kallax.Record {
				return new(ReviewEvent)
			},
			false,
			kallax.NewSchemaField("id"),
			kallax.NewSchemaField("status"),
			kallax.NewSchemaField("provider"),
			kallax.NewSchemaField("internal_id"),
			kallax.NewSchemaField("created_at"),
			kallax.NewSchemaField("updated_at"),
			kallax.NewSchemaField("is_mergeable"),
			kallax.NewSchemaField("source"),
			kallax.NewSchemaField("merge"),
			kallax.NewSchemaField("configuration"),
			kallax.NewSchemaField("base"),
			kallax.NewSchemaField("head"),
		),
		ID:          kallax.NewSchemaField("id"),
		Status:      kallax.NewSchemaField("status"),
		Provider:    kallax.NewSchemaField("provider"),
		InternalID:  kallax.NewSchemaField("internal_id"),
		CreatedAt:   kallax.NewSchemaField("created_at"),
		UpdatedAt:   kallax.NewSchemaField("updated_at"),
		IsMergeable: kallax.NewSchemaField("is_mergeable"),
		Source: &schemaReviewEventSource{
			BaseSchemaField:       kallax.NewSchemaField("source").(*kallax.BaseSchemaField),
			InternalRepositoryURL: kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "source", "internal_repository_url"),
			ReferenceName:         kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "source", "reference_name"),
			Hash:                  kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "source", "hash"),
		},
		Merge: &schemaReviewEventMerge{
			BaseSchemaField:       kallax.NewSchemaField("merge").(*kallax.BaseSchemaField),
			InternalRepositoryURL: kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "merge", "internal_repository_url"),
			ReferenceName:         kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "merge", "reference_name"),
			Hash:                  kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "merge", "hash"),
		},
		Configuration: &schemaReviewEventConfiguration{
			BaseSchemaField: kallax.NewSchemaField("configuration").(*kallax.BaseSchemaField),
			Fields:          kallax.NewJSONSchemaKey(kallax.JSONAny, "review_event", "configuration", "fields"),
		},
		Base: &schemaReviewEventBase{
			BaseSchemaField:       kallax.NewSchemaField("base").(*kallax.BaseSchemaField),
			InternalRepositoryURL: kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "base", "internal_repository_url"),
			ReferenceName:         kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "base", "reference_name"),
			Hash:                  kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "base", "hash"),
		},
		Head: &schemaReviewEventHead{
			BaseSchemaField:       kallax.NewSchemaField("head").(*kallax.BaseSchemaField),
			InternalRepositoryURL: kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "head", "internal_repository_url"),
			ReferenceName:         kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "head", "reference_name"),
			Hash:                  kallax.NewJSONSchemaKey(kallax.JSONText, "review_event", "head", "hash"),
		},
	},
}
