app:
  lookout:
    logLevel: debug
    bblfshdConnectionString: ipv4://lookout-bblfshd-bblfshd:9432

databases:
  postgres:
    cloudSQL: true
    instanceConnectionName: srcd-public-staging:europe-west1:lookout-staging-primary
    serviceAccountSecret: cloudsql-proxy-credentials
    connectionDetailsSecret: lookout-postgres-connection-details

queues:
  rabbitmq:
    connectionString: amqp://lookout-rabbitmq-ha:5672

nodeSelector:
  lookout:
    srcd.host/app: lookout

repositories:
  - url: github.com/src-d/lookout
  - url: github.com/bblfsh/uast-viewer

providers:
  github:
    app_id: 17877
    private_key: /local/lookout/private-key.pem
    secretName: lookout-staging-github-key
    comment_footer: "_{{if .Feedback}}If you have feedback about this comment made by the analyzer {{.Name}}, please, [tell us]({{.Feedback}}){{else}}Comment made by the analyzer {{.Name}}{{end}}._"
    installation_sync_interval: 5m

analyzers:
  - name: style-analyzer
    addr: ipv4://lookout-style-analyzer:2000
    feedback: https://github.com/src-d/style-analyzer/issues/new
  - name: gometalint-analyzer
    addr: ipv4://lookout-gometalint-analyzer:10303
    feedback: https://github.com/src-d/lookout-gometalint-analyzer/issues/new
  - name: sonarcheck-analyzer
    addr: ipv4://lookout-sonarcheck-analyzer:10304
    feedback: https://github.com/src-d/lookout-sonarcheck-analyzer/issues/new
  - name: terraform-analyzer
    addr: ipv4://lookout-terraform-analyzer:10303
    feedback: https://github.com/src-d/lookout-terraform-analyzer/issues/new

bblfshd-sidecar:
  metrics:
    enabled: true
    namespace: lookout
    additionalServiceMatchLabels:
      app: lookout-work
  image:
    tag: v2.14.0
  drivers:
    install: true
    languages:
      # for js we have to lock old version due to style-analyzer
      javascript:
        repository: bblfsh/javascript-driver
        tag: v2.7.1
      # for the rest we can use latest
      python:
        repository: bblfsh/python-driver
        tag: v2.8.3
      cpp:
        repository: bblfsh/cpp-driver
        tag: v1.2.4
      java:
        repository: bblfsh/java-driver
        tag: v2.6.3
      bash:
        repository: bblfsh/bash-driver
        tag: v2.5.2
      ruby:
        repository: bblfsh/ruby-driver
        tag: v2.9.2
      go:
        repository: bblfsh/go-driver
        tag: v2.5.3
      csharp:
        repository: bblfsh/csharp-driver
        tag: v1.4.3
      php:
        repository: bblfsh/php-driver
        tag: v2.7.4
