app:
  lookout:
    repository: github.com/src-d/lookout,github.com/bblfsh/uast-viewer
    logLevel: debug
    secretName: lookout-github-credentials
    dbConnectionString: postgres://lookout:lookout@lookout-postgresql:5432/lookout?sslmode=disable
    bblfshdConnectionString: ipv4://lookout-bblfshd-bblfshd:9432

nodeSelector:
 lookout:
   srcd.host/type: worker

nodeSelector:
 dummyAnalyzer:
   srcd.host/type: worker

providers:
  github:
    comment_footer: "_If you have feedback about this comment, please, [tell us](%s)._"

analyzers:
  - name: style-analyzer
    addr: ipv4://lookout-style-analyzer:2000
    feedback: https://github.com/src-d/style-analyzer/issues/new
  - name: gometalint-analyzer
    addr: ipv4://lookout-gometalint-analyzer:10303
    feedback: https://github.com/src-d/lookout-gometalint-analyzer/issues/new
