# Package configuration
PROJECT = lookout-dummy-analyzer
COMMANDS = cmd/dummy

# Including ci Makefile
CI_REPOSITORY ?= https://github.com/src-d/ci.git
CI_BRANCH ?= v1
CI_PATH ?= .ci
MAKEFILE := $(CI_PATH)/Makefile.main
$(MAKEFILE):
	git clone --quiet --depth 1 -b $(CI_BRANCH) $(CI_REPOSITORY) $(CI_PATH);
-include $(MAKEFILE)

# Dummy analyzer dockerfile
DOCKERFILES=./docker/Dockerfile.dummy:$(PROJECT)
